openapi: 3.0.3
info:
  title: Kontrakt Spec
  version: 0.1.0
servers:
  - url: "http://localhost:8080"
paths:
  /api/login:
    post:
      operationId: "post__api_login"
      requestBody:
        content:
          application/json:
            example:
              username: "admin"
              password: "1234"
      responses:
        "200":
          description: "Login successful"
          headers:
            Content-Type:
              schema:
                type: string
              description: "contains json"
          content:
            application/json:
              example:
                success: true
                token: ""
                message: "Login successful"
        "401":
          description: "Invalid credentials"
          content:
            application/json:
              example:
                success: false
                message: "Invalid credentials"
  /api/users/42:
    get:
      operationId: "get__api_users_42"
      responses:
        "200":
          description: "Response 200"
          headers:
            Content-Type:
              schema:
                type: string
              description: "contains json"
          content:
            application/json:
              example:
                id: 42
                username: "user42"
                email: "user42@example.com"
                role: "USER"
    put:
      operationId: "put__api_users_42"
      requestBody:
        content:
          application/json:
            example:
              role: "ADMIN"
      responses:
        "200":
          description: "User updated successfully"
          headers:
            Content-Type:
              schema:
                type: string
              description: "contains json"
          content:
            application/json:
              example:
                id: 42
                updated: true
                role: "ADMIN"
                message: "User updated successfully"
  /api/users/99:
    delete:
      operationId: "delete__api_users_99"
      responses:
        "200":
          description: "User deleted successfully"
          headers:
            Content-Type:
              schema:
                type: string
              description: "contains json"
          content:
            application/json:
              example:
                id: 99
                deleted: true
                message: "User deleted successfully"
  /api/users/9999:
    get:
      operationId: "get__api_users_9999"
      responses:
        "404":
          description: "Response 404"
