
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACE = 12;
  public static final int PUT = 7;
  public static final int NUMBER = 9;
  public static final int STATUS = 15;
  public static final int STRING = 11;
  public static final int EOF = 0;
  public static final int EXPECT = 4;
  public static final int TEST = 3;
  public static final int DELETE = 8;
  public static final int error = 1;
  public static final int SEMICOLON = 14;
  public static final int IDENTIFIER = 10;
  public static final int POST = 6;
  public static final int GET = 5;
  public static final int EQUALS = 16;
  public static final int RBRACE = 13;
  public static final int CONFIG = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONFIG",
  "TEST",
  "EXPECT",
  "GET",
  "POST",
  "PUT",
  "DELETE",
  "NUMBER",
  "IDENTIFIER",
  "STRING",
  "LBRACE",
  "RBRACE",
  "SEMICOLON",
  "STATUS",
  "EQUALS"
  };
}

